version: '3.1'
services:
  db:
    container_name: pg_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db1
    ports:
      - '1000:5432'
  app:
    container_name: app1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2000:8088'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db1
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db